types:
  DeploymentsListRequestStatus:
    enum:
      - ACTIVE
      - ARCHIVED
    source:
      openapi: openapi/openapi.yml
  ListDeploymentReleaseTagsRequestSource:
    enum:
      - SYSTEM
      - USER
    source:
      openapi: openapi/openapi.yml
imports:
  root: __package__.yml
service:
  auth: false
  base-path: ''
  endpoints:
    list:
      path: /v1/deployments
      method: GET
      auth: true
      docs: Used to list all Prompt Deployments.
      request:
        name: DeploymentsListRequest
        query-parameters:
          limit:
            type: optional<integer>
            docs: Number of results to return per page.
          offset:
            type: optional<integer>
            docs: The initial index from which to return the results.
          ordering:
            type: optional<string>
            docs: Which field to use when ordering the results.
          status:
            type: optional<DeploymentsListRequestStatus>
            docs: status
      response:
        docs: ''
        type: root.PaginatedSlimDeploymentReadList
      url: Default
      availability: pre-release
      examples:
        - response:
            body:
              count: 123
              next: http://api.example.org/accounts/?offset=400&limit=100
              previous: http://api.example.org/accounts/?offset=200&limit=100
              results:
                - id: id
                  created: '2024-01-15T09:30:00Z'
                  label: label
                  name: name
                  status: ACTIVE
                  environment: DEVELOPMENT
                  last_deployed_on: '2024-01-15T09:30:00Z'
                  input_variables:
                    - id: id
                      key: key
                      type: STRING
                  description: description
      audiences:
        - customers
    retrieve:
      path: /v1/deployments/{id}
      method: GET
      auth: true
      docs: Used to retrieve a Prompt Deployment given its ID or name.
      path-parameters:
        id:
          type: string
          docs: Either the Deployment's ID or its unique name
      response:
        docs: ''
        type: root.DeploymentRead
      url: Default
      availability: pre-release
      examples:
        - path-parameters:
            id: id
          response:
            body:
              id: id
              created: '2024-01-15T09:30:00Z'
              label: label
              name: name
              status: ACTIVE
              environment: DEVELOPMENT
              last_deployed_on: '2024-01-15T09:30:00Z'
              input_variables:
                - id: id
                  key: key
                  type: STRING
                  required: true
                  default:
                    type: STRING
              description: description
              active_model_version_ids:
                - active_model_version_ids
              last_deployed_history_item_id: last_deployed_history_item_id
      audiences:
        - customers
    deployment_history_item_retrieve:
      path: /v1/deployments/{id}/history/{history_id_or_release_tag}
      method: GET
      auth: true
      docs: >-
        Retrieve a specific Deployment History Item by either its UUID or the
        name of a Release Tag that points to it.
      path-parameters:
        history_id_or_release_tag:
          type: string
          docs: >-
            Either the UUID of Deployment History Item you'd like to retrieve,
            or the name of a Release Tag that's pointing to the Deployment
            History Item you'd like to retrieve.
        id:
          type: string
          docs: A UUID string identifying this deployment.
      response:
        docs: ''
        type: root.DeploymentHistoryItem
      url: Default
      availability: pre-release
      examples:
        - path-parameters:
            history_id_or_release_tag: history_id_or_release_tag
            id: id
          response:
            body:
              id: id
              deployment_id: deployment_id
              timestamp: '2024-01-15T09:30:00Z'
              label: label
              name: name
              input_variables:
                - id: id
                  key: key
                  type: STRING
                  required: true
                  default:
                    type: STRING
              description: description
      audiences:
        - customers
    list_deployment_release_tags:
      path: /v1/deployments/{id}/release-tags
      method: GET
      auth: true
      docs: List Release Tags associated with the specified Prompt Deployment
      path-parameters:
        id:
          type: string
          docs: Either the Prompt Deployment's ID or its unique name
      request:
        name: ListDeploymentReleaseTagsRequest
        query-parameters:
          limit:
            type: optional<integer>
            docs: Number of results to return per page.
          offset:
            type: optional<integer>
            docs: The initial index from which to return the results.
          ordering:
            type: optional<string>
            docs: Which field to use when ordering the results.
          source: optional<ListDeploymentReleaseTagsRequestSource>
      response:
        docs: ''
        type: root.PaginatedDeploymentReleaseTagReadList
      url: Default
      availability: pre-release
      examples:
        - path-parameters:
            id: id
          response:
            body:
              count: 123
              next: http://api.example.org/accounts/?offset=400&limit=100
              previous: http://api.example.org/accounts/?offset=200&limit=100
              results:
                - name: name
                  source: SYSTEM
                  history_item:
                    id: id
                    timestamp: '2024-01-15T09:30:00Z'
      audiences:
        - customers
    retrieve_deployment_release_tag:
      path: /v1/deployments/{id}/release-tags/{name}
      method: GET
      auth: true
      docs: >-
        Retrieve a Deployment Release Tag by tag name, associated with a
        specified Deployment.
      path-parameters:
        id:
          type: string
          docs: A UUID string identifying this deployment.
        name:
          type: string
          docs: >-
            The name of the Release Tag associated with this Deployment that
            you'd like to retrieve.
      response:
        docs: ''
        type: root.DeploymentReleaseTagRead
      url: Default
      availability: pre-release
      examples:
        - path-parameters:
            id: id
            name: name
          response:
            body:
              name: name
              source: SYSTEM
              history_item:
                id: id
                timestamp: '2024-01-15T09:30:00Z'
      audiences:
        - customers
    update_deployment_release_tag:
      path: /v1/deployments/{id}/release-tags/{name}
      method: PATCH
      auth: true
      docs: >-
        Updates an existing Release Tag associated with the specified Prompt
        Deployment.
      path-parameters:
        id:
          type: string
          docs: A UUID string identifying this deployment.
        name:
          type: string
          docs: >-
            The name of the Release Tag associated with this Deployment that
            you'd like to update.
      request:
        name: PatchedDeploymentReleaseTagUpdateRequest
        body:
          properties:
            history_item_id:
              type: optional<string>
              docs: The ID of the Deployment History Item to tag
              validation:
                format: uuid
      response:
        docs: ''
        type: root.DeploymentReleaseTagRead
      url: Default
      availability: pre-release
      examples:
        - path-parameters:
            id: id
            name: name
          request: {}
          response:
            body:
              name: name
              source: SYSTEM
              history_item:
                id: id
                timestamp: '2024-01-15T09:30:00Z'
      audiences:
        - customers
    retrieve_provider_payload:
      path: /v1/deployments/provider-payload
      method: POST
      auth: true
      docs: >
        Given a set of input variable values, compile the exact payload that
        Vellum would send to the configured model provider

        for execution if the execute-prompt endpoint had been invoked. Note that
        this endpoint does not actually execute the

        prompt or make an API call to the model provider.


        This endpoint is useful if you don't want to proxy LLM provider requests
        through Vellum and prefer to send them directly

        to the provider yourself. Note that no guarantees are made on the format
        of this API's response schema, other than

        that it will be a valid payload for the configured model provider. It's
        not recommended that you try to parse or

        derive meaning from the response body and instead, should simply pass it
        directly to the model provider as is.


        We encourage you to seek advise from Vellum Support before integrating
        with this API for production use.
      request:
        name: DeploymentProviderPayloadRequest
        body:
          properties:
            deployment_id:
              type: optional<string>
              docs: >-
                The ID of the deployment. Must provide either this or
                deployment_name.
              validation:
                format: uuid
            deployment_name:
              type: optional<string>
              docs: >-
                The name of the deployment. Must provide either this or
                deployment_id.
              validation:
                minLength: 1
            inputs:
              docs: >-
                The list of inputs defined in the Prompt's deployment with their
                corresponding values.
              type: list<root.PromptDeploymentInputRequest>
            release_tag:
              type: optional<string>
              docs: >-
                Optionally specify a release tag if you want to pin to a
                specific release of the Workflow Deployment
              validation:
                minLength: 1
            expand_meta: optional<root.CompilePromptDeploymentExpandMetaRequest>
      response:
        docs: ''
        type: root.DeploymentProviderPayloadResponse
      url: Default
      availability: pre-release
      errors:
        - root.BadRequestError
        - root.ForbiddenError
        - root.NotFoundError
        - root.InternalServerError
      examples:
        - request:
            inputs:
              - name: name
                type: STRING
                value: value
          response:
            body:
              payload:
                key: value
              meta:
                model_name: model_name
                deployment_release_tag: deployment_release_tag
                prompt_version_id: prompt_version_id
      audiences:
        - customers
  source:
    openapi: openapi/openapi.yml
