// This file was auto-generated by Fern from our API Definition.

package api

type AdHocExecutePromptStreamRequest struct {
	MlModel        string                         `json:"ml_model" url:"-"`
	InputValues    []*PromptRequestInputRequest   `json:"input_values,omitempty" url:"-"`
	InputVariables []*VellumVariableRequest       `json:"input_variables,omitempty" url:"-"`
	Parameters     *PromptParametersRequest       `json:"parameters,omitempty" url:"-"`
	Blocks         []*PromptBlockRequest          `json:"blocks,omitempty" url:"-"`
	ExpandMeta     *AdHocExpandMetaRequestRequest `json:"expand_meta,omitempty" url:"-"`
}
