// This file was auto-generated by Fern from our API Definition.

package api

type ContainerImagesListRequest struct {
	// Number of results to return per page.
	Limit *int `json:"-" url:"limit,omitempty"`
	// The initial index from which to return the results.
	Offset *int `json:"-" url:"offset,omitempty"`
	// Which field to use when ordering the results.
	Ordering *string `json:"-" url:"ordering,omitempty"`
}

type PushContainerImageRequest struct {
	Name string   `json:"name" url:"-"`
	Sha  string   `json:"sha" url:"-"`
	Tags []string `json:"tags,omitempty" url:"-"`
}
