// This file was auto-generated by Fern from our API Definition.

package api

type DeploymentProviderPayloadRequest struct {
	// The ID of the deployment. Must provide either this or deployment_name.
	DeploymentId *string `json:"deployment_id,omitempty"`
	// The name of the deployment. Must provide either this or deployment_id.
	DeploymentName *string                         `json:"deployment_name,omitempty"`
	Inputs         []*PromptDeploymentInputRequest `json:"inputs,omitempty"`
}
