// This file was auto-generated by Fern from our API Definition.

package api

// Environments defines all of the API environments.
// These values can be used with the WithBaseURL
// ClientOption to override the client's default environment,
// if any.
var Environments = struct {
	Production struct {
		Default   string
		Documents string
		Predict   string
	}
}{
	Production: struct {
		Default   string
		Documents string
		Predict   string
	}{
		Default:   "https://api.vellum.ai",
		Documents: "https://documents.vellum.ai",
		Predict:   "https://predict.vellum.ai",
	},
}
