// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/vellum-ai/vellum-client-go/core"
	time "time"
)

type AddEntityToFolderRequest struct {
	// The ID of the entity you would like to move.
	EntityID string `json:"entity_id" url:"-"`
}

type FolderEntitiesListRequest struct {
	// Filter down to only those objects whose entities have a status matching the status specified.
	//
	// * `ACTIVE` - Active
	// * `ARCHIVED` - Archived
	EntityStatus *FolderEntitiesListRequestEntityStatus `json:"-" url:"entity_status,omitempty"`
	// Number of results to return per page.
	Limit *int `json:"-" url:"limit,omitempty"`
	// The initial index from which to return the results.
	Offset *int `json:"-" url:"offset,omitempty"`
	// Which field to use when ordering the results.
	Ordering *string `json:"-" url:"ordering,omitempty"`
	// Filter down to only those entities whose parent folder has the specified ID.
	//
	// To filter by an entity's parent folder, provide the ID of the parent folder. To filter by the root directory, provide
	// a string representing the entity type of the root directory. Supported root directories include:
	// - PROMPT_SANDBOX
	// - WORKFLOW_SANDBOX
	// - DOCUMENT_INDEX
	// - TEST_SUITE
	ParentFolderID string `json:"-" url:"parent_folder_id"`
}

type FolderEntity struct {
	Type            string
	Folder          *FolderEntityFolder
	PromptSandbox   *FolderEntityPromptSandbox
	WorkflowSandbox *FolderEntityWorkflowSandbox
	DocumentIndex   *FolderEntityDocumentIndex
	TestSuite       *FolderEntityTestSuite
	Dataset         *FolderEntityDataset
}

func (f *FolderEntity) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	f.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", f)
	}
	switch unmarshaler.Type {
	case "FOLDER":
		value := new(FolderEntityFolder)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.Folder = value
	case "PROMPT_SANDBOX":
		value := new(FolderEntityPromptSandbox)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.PromptSandbox = value
	case "WORKFLOW_SANDBOX":
		value := new(FolderEntityWorkflowSandbox)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.WorkflowSandbox = value
	case "DOCUMENT_INDEX":
		value := new(FolderEntityDocumentIndex)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.DocumentIndex = value
	case "TEST_SUITE":
		value := new(FolderEntityTestSuite)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.TestSuite = value
	case "DATASET":
		value := new(FolderEntityDataset)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.Dataset = value
	}
	return nil
}

func (f FolderEntity) MarshalJSON() ([]byte, error) {
	if f.Folder != nil {
		return core.MarshalJSONWithExtraProperty(f.Folder, "type", "FOLDER")
	}
	if f.PromptSandbox != nil {
		return core.MarshalJSONWithExtraProperty(f.PromptSandbox, "type", "PROMPT_SANDBOX")
	}
	if f.WorkflowSandbox != nil {
		return core.MarshalJSONWithExtraProperty(f.WorkflowSandbox, "type", "WORKFLOW_SANDBOX")
	}
	if f.DocumentIndex != nil {
		return core.MarshalJSONWithExtraProperty(f.DocumentIndex, "type", "DOCUMENT_INDEX")
	}
	if f.TestSuite != nil {
		return core.MarshalJSONWithExtraProperty(f.TestSuite, "type", "TEST_SUITE")
	}
	if f.Dataset != nil {
		return core.MarshalJSONWithExtraProperty(f.Dataset, "type", "DATASET")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", f)
}

type FolderEntityVisitor interface {
	VisitFolder(*FolderEntityFolder) error
	VisitPromptSandbox(*FolderEntityPromptSandbox) error
	VisitWorkflowSandbox(*FolderEntityWorkflowSandbox) error
	VisitDocumentIndex(*FolderEntityDocumentIndex) error
	VisitTestSuite(*FolderEntityTestSuite) error
	VisitDataset(*FolderEntityDataset) error
}

func (f *FolderEntity) Accept(visitor FolderEntityVisitor) error {
	if f.Folder != nil {
		return visitor.VisitFolder(f.Folder)
	}
	if f.PromptSandbox != nil {
		return visitor.VisitPromptSandbox(f.PromptSandbox)
	}
	if f.WorkflowSandbox != nil {
		return visitor.VisitWorkflowSandbox(f.WorkflowSandbox)
	}
	if f.DocumentIndex != nil {
		return visitor.VisitDocumentIndex(f.DocumentIndex)
	}
	if f.TestSuite != nil {
		return visitor.VisitTestSuite(f.TestSuite)
	}
	if f.Dataset != nil {
		return visitor.VisitDataset(f.Dataset)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", f)
}

// A slim representation of a Dataset, as it exists within a Folder.
type FolderEntityDataset struct {
	ID   string                   `json:"id" url:"id"`
	Data *FolderEntityDatasetData `json:"data" url:"data"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (f *FolderEntityDataset) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FolderEntityDataset) UnmarshalJSON(data []byte) error {
	type unmarshaler FolderEntityDataset
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FolderEntityDataset(value)

	extraProperties, err := core.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties

	f._rawJSON = json.RawMessage(data)
	return nil
}

func (f *FolderEntityDataset) String() string {
	if len(f._rawJSON) > 0 {
		if value, err := core.StringifyJSON(f._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

type FolderEntityDatasetData struct {
	ID          string    `json:"id" url:"id"`
	Label       string    `json:"label" url:"label"`
	Name        string    `json:"name" url:"name"`
	Description *string   `json:"description,omitempty" url:"description,omitempty"`
	Created     time.Time `json:"created" url:"created"`
	Modified    time.Time `json:"modified" url:"modified"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (f *FolderEntityDatasetData) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FolderEntityDatasetData) UnmarshalJSON(data []byte) error {
	type embed FolderEntityDatasetData
	var unmarshaler = struct {
		embed
		Created  *core.DateTime `json:"created"`
		Modified *core.DateTime `json:"modified"`
	}{
		embed: embed(*f),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*f = FolderEntityDatasetData(unmarshaler.embed)
	f.Created = unmarshaler.Created.Time()
	f.Modified = unmarshaler.Modified.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties

	f._rawJSON = json.RawMessage(data)
	return nil
}

func (f *FolderEntityDatasetData) MarshalJSON() ([]byte, error) {
	type embed FolderEntityDatasetData
	var marshaler = struct {
		embed
		Created  *core.DateTime `json:"created"`
		Modified *core.DateTime `json:"modified"`
	}{
		embed:    embed(*f),
		Created:  core.NewDateTime(f.Created),
		Modified: core.NewDateTime(f.Modified),
	}
	return json.Marshal(marshaler)
}

func (f *FolderEntityDatasetData) String() string {
	if len(f._rawJSON) > 0 {
		if value, err := core.StringifyJSON(f._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// A slim representation of a Document Index, as it exists within a Folder.
type FolderEntityDocumentIndex struct {
	ID   string                         `json:"id" url:"id"`
	Data *FolderEntityDocumentIndexData `json:"data" url:"data"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (f *FolderEntityDocumentIndex) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FolderEntityDocumentIndex) UnmarshalJSON(data []byte) error {
	type unmarshaler FolderEntityDocumentIndex
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FolderEntityDocumentIndex(value)

	extraProperties, err := core.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties

	f._rawJSON = json.RawMessage(data)
	return nil
}

func (f *FolderEntityDocumentIndex) String() string {
	if len(f._rawJSON) > 0 {
		if value, err := core.StringifyJSON(f._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

type FolderEntityDocumentIndexData struct {
	ID             string                       `json:"id" url:"id"`
	Label          string                       `json:"label" url:"label"`
	Created        time.Time                    `json:"created" url:"created"`
	Modified       time.Time                    `json:"modified" url:"modified"`
	Status         EntityStatus                 `json:"status" url:"status"`
	IndexingConfig *DocumentIndexIndexingConfig `json:"indexing_config" url:"indexing_config"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (f *FolderEntityDocumentIndexData) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FolderEntityDocumentIndexData) UnmarshalJSON(data []byte) error {
	type embed FolderEntityDocumentIndexData
	var unmarshaler = struct {
		embed
		Created  *core.DateTime `json:"created"`
		Modified *core.DateTime `json:"modified"`
	}{
		embed: embed(*f),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*f = FolderEntityDocumentIndexData(unmarshaler.embed)
	f.Created = unmarshaler.Created.Time()
	f.Modified = unmarshaler.Modified.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties

	f._rawJSON = json.RawMessage(data)
	return nil
}

func (f *FolderEntityDocumentIndexData) MarshalJSON() ([]byte, error) {
	type embed FolderEntityDocumentIndexData
	var marshaler = struct {
		embed
		Created  *core.DateTime `json:"created"`
		Modified *core.DateTime `json:"modified"`
	}{
		embed:    embed(*f),
		Created:  core.NewDateTime(f.Created),
		Modified: core.NewDateTime(f.Modified),
	}
	return json.Marshal(marshaler)
}

func (f *FolderEntityDocumentIndexData) String() string {
	if len(f._rawJSON) > 0 {
		if value, err := core.StringifyJSON(f._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// A slim representation of a Folder, as it exists within another Folder.
type FolderEntityFolder struct {
	ID   string                  `json:"id" url:"id"`
	Data *FolderEntityFolderData `json:"data" url:"data"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (f *FolderEntityFolder) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FolderEntityFolder) UnmarshalJSON(data []byte) error {
	type unmarshaler FolderEntityFolder
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FolderEntityFolder(value)

	extraProperties, err := core.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties

	f._rawJSON = json.RawMessage(data)
	return nil
}

func (f *FolderEntityFolder) String() string {
	if len(f._rawJSON) > 0 {
		if value, err := core.StringifyJSON(f._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

type FolderEntityFolderData struct {
	ID          string    `json:"id" url:"id"`
	Label       string    `json:"label" url:"label"`
	Created     time.Time `json:"created" url:"created"`
	Modified    time.Time `json:"modified" url:"modified"`
	HasContents bool      `json:"has_contents" url:"has_contents"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (f *FolderEntityFolderData) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FolderEntityFolderData) UnmarshalJSON(data []byte) error {
	type embed FolderEntityFolderData
	var unmarshaler = struct {
		embed
		Created  *core.DateTime `json:"created"`
		Modified *core.DateTime `json:"modified"`
	}{
		embed: embed(*f),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*f = FolderEntityFolderData(unmarshaler.embed)
	f.Created = unmarshaler.Created.Time()
	f.Modified = unmarshaler.Modified.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties

	f._rawJSON = json.RawMessage(data)
	return nil
}

func (f *FolderEntityFolderData) MarshalJSON() ([]byte, error) {
	type embed FolderEntityFolderData
	var marshaler = struct {
		embed
		Created  *core.DateTime `json:"created"`
		Modified *core.DateTime `json:"modified"`
	}{
		embed:    embed(*f),
		Created:  core.NewDateTime(f.Created),
		Modified: core.NewDateTime(f.Modified),
	}
	return json.Marshal(marshaler)
}

func (f *FolderEntityFolderData) String() string {
	if len(f._rawJSON) > 0 {
		if value, err := core.StringifyJSON(f._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// A slim representation of a Prompt Sandbox, as it exists within a Folder.
type FolderEntityPromptSandbox struct {
	ID   string                         `json:"id" url:"id"`
	Data *FolderEntityPromptSandboxData `json:"data" url:"data"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (f *FolderEntityPromptSandbox) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FolderEntityPromptSandbox) UnmarshalJSON(data []byte) error {
	type unmarshaler FolderEntityPromptSandbox
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FolderEntityPromptSandbox(value)

	extraProperties, err := core.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties

	f._rawJSON = json.RawMessage(data)
	return nil
}

func (f *FolderEntityPromptSandbox) String() string {
	if len(f._rawJSON) > 0 {
		if value, err := core.StringifyJSON(f._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

type FolderEntityPromptSandboxData struct {
	ID             string       `json:"id" url:"id"`
	Label          string       `json:"label" url:"label"`
	Created        time.Time    `json:"created" url:"created"`
	Modified       time.Time    `json:"modified" url:"modified"`
	Status         EntityStatus `json:"status" url:"status"`
	Description    *string      `json:"description,omitempty" url:"description,omitempty"`
	LastDeployedOn *time.Time   `json:"last_deployed_on,omitempty" url:"last_deployed_on,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (f *FolderEntityPromptSandboxData) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FolderEntityPromptSandboxData) UnmarshalJSON(data []byte) error {
	type embed FolderEntityPromptSandboxData
	var unmarshaler = struct {
		embed
		Created        *core.DateTime `json:"created"`
		Modified       *core.DateTime `json:"modified"`
		LastDeployedOn *core.DateTime `json:"last_deployed_on,omitempty"`
	}{
		embed: embed(*f),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*f = FolderEntityPromptSandboxData(unmarshaler.embed)
	f.Created = unmarshaler.Created.Time()
	f.Modified = unmarshaler.Modified.Time()
	f.LastDeployedOn = unmarshaler.LastDeployedOn.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties

	f._rawJSON = json.RawMessage(data)
	return nil
}

func (f *FolderEntityPromptSandboxData) MarshalJSON() ([]byte, error) {
	type embed FolderEntityPromptSandboxData
	var marshaler = struct {
		embed
		Created        *core.DateTime `json:"created"`
		Modified       *core.DateTime `json:"modified"`
		LastDeployedOn *core.DateTime `json:"last_deployed_on,omitempty"`
	}{
		embed:          embed(*f),
		Created:        core.NewDateTime(f.Created),
		Modified:       core.NewDateTime(f.Modified),
		LastDeployedOn: core.NewOptionalDateTime(f.LastDeployedOn),
	}
	return json.Marshal(marshaler)
}

func (f *FolderEntityPromptSandboxData) String() string {
	if len(f._rawJSON) > 0 {
		if value, err := core.StringifyJSON(f._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// A slim representation of a Test Suite, as it exists within a Folder.
type FolderEntityTestSuite struct {
	ID   string                     `json:"id" url:"id"`
	Data *FolderEntityTestSuiteData `json:"data" url:"data"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (f *FolderEntityTestSuite) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FolderEntityTestSuite) UnmarshalJSON(data []byte) error {
	type unmarshaler FolderEntityTestSuite
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FolderEntityTestSuite(value)

	extraProperties, err := core.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties

	f._rawJSON = json.RawMessage(data)
	return nil
}

func (f *FolderEntityTestSuite) String() string {
	if len(f._rawJSON) > 0 {
		if value, err := core.StringifyJSON(f._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

type FolderEntityTestSuiteData struct {
	ID       string       `json:"id" url:"id"`
	Label    string       `json:"label" url:"label"`
	Created  time.Time    `json:"created" url:"created"`
	Modified time.Time    `json:"modified" url:"modified"`
	Status   EntityStatus `json:"status" url:"status"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (f *FolderEntityTestSuiteData) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FolderEntityTestSuiteData) UnmarshalJSON(data []byte) error {
	type embed FolderEntityTestSuiteData
	var unmarshaler = struct {
		embed
		Created  *core.DateTime `json:"created"`
		Modified *core.DateTime `json:"modified"`
	}{
		embed: embed(*f),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*f = FolderEntityTestSuiteData(unmarshaler.embed)
	f.Created = unmarshaler.Created.Time()
	f.Modified = unmarshaler.Modified.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties

	f._rawJSON = json.RawMessage(data)
	return nil
}

func (f *FolderEntityTestSuiteData) MarshalJSON() ([]byte, error) {
	type embed FolderEntityTestSuiteData
	var marshaler = struct {
		embed
		Created  *core.DateTime `json:"created"`
		Modified *core.DateTime `json:"modified"`
	}{
		embed:    embed(*f),
		Created:  core.NewDateTime(f.Created),
		Modified: core.NewDateTime(f.Modified),
	}
	return json.Marshal(marshaler)
}

func (f *FolderEntityTestSuiteData) String() string {
	if len(f._rawJSON) > 0 {
		if value, err := core.StringifyJSON(f._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// A slim representation of a Workflow Sandbox, as it exists within a Folder.
type FolderEntityWorkflowSandbox struct {
	ID   string                           `json:"id" url:"id"`
	Data *FolderEntityWorkflowSandboxData `json:"data" url:"data"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (f *FolderEntityWorkflowSandbox) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FolderEntityWorkflowSandbox) UnmarshalJSON(data []byte) error {
	type unmarshaler FolderEntityWorkflowSandbox
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FolderEntityWorkflowSandbox(value)

	extraProperties, err := core.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties

	f._rawJSON = json.RawMessage(data)
	return nil
}

func (f *FolderEntityWorkflowSandbox) String() string {
	if len(f._rawJSON) > 0 {
		if value, err := core.StringifyJSON(f._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

type FolderEntityWorkflowSandboxData struct {
	ID             string                      `json:"id" url:"id"`
	Label          string                      `json:"label" url:"label"`
	Created        time.Time                   `json:"created" url:"created"`
	Modified       time.Time                   `json:"modified" url:"modified"`
	Status         EntityStatus                `json:"status" url:"status"`
	Description    *string                     `json:"description,omitempty" url:"description,omitempty"`
	LastDeployedOn *time.Time                  `json:"last_deployed_on,omitempty" url:"last_deployed_on,omitempty"`
	DisplayData    *WorkflowSandboxDisplayData `json:"display_data,omitempty" url:"display_data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (f *FolderEntityWorkflowSandboxData) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FolderEntityWorkflowSandboxData) UnmarshalJSON(data []byte) error {
	type embed FolderEntityWorkflowSandboxData
	var unmarshaler = struct {
		embed
		Created        *core.DateTime `json:"created"`
		Modified       *core.DateTime `json:"modified"`
		LastDeployedOn *core.DateTime `json:"last_deployed_on,omitempty"`
	}{
		embed: embed(*f),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*f = FolderEntityWorkflowSandboxData(unmarshaler.embed)
	f.Created = unmarshaler.Created.Time()
	f.Modified = unmarshaler.Modified.Time()
	f.LastDeployedOn = unmarshaler.LastDeployedOn.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties

	f._rawJSON = json.RawMessage(data)
	return nil
}

func (f *FolderEntityWorkflowSandboxData) MarshalJSON() ([]byte, error) {
	type embed FolderEntityWorkflowSandboxData
	var marshaler = struct {
		embed
		Created        *core.DateTime `json:"created"`
		Modified       *core.DateTime `json:"modified"`
		LastDeployedOn *core.DateTime `json:"last_deployed_on,omitempty"`
	}{
		embed:          embed(*f),
		Created:        core.NewDateTime(f.Created),
		Modified:       core.NewDateTime(f.Modified),
		LastDeployedOn: core.NewOptionalDateTime(f.LastDeployedOn),
	}
	return json.Marshal(marshaler)
}

func (f *FolderEntityWorkflowSandboxData) String() string {
	if len(f._rawJSON) > 0 {
		if value, err := core.StringifyJSON(f._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

type PaginatedFolderEntityList struct {
	Count    *int            `json:"count,omitempty" url:"count,omitempty"`
	Next     *string         `json:"next,omitempty" url:"next,omitempty"`
	Previous *string         `json:"previous,omitempty" url:"previous,omitempty"`
	Results  []*FolderEntity `json:"results,omitempty" url:"results,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PaginatedFolderEntityList) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaginatedFolderEntityList) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginatedFolderEntityList
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginatedFolderEntityList(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginatedFolderEntityList) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Information used to display this Workflow Sandbox.
type WorkflowSandboxDisplayData struct {
	// The icon associated with this Workflow Sandbox.
	Icon *WorkflowDisplayIcon `json:"icon,omitempty" url:"icon,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (w *WorkflowSandboxDisplayData) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkflowSandboxDisplayData) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowSandboxDisplayData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkflowSandboxDisplayData(value)

	extraProperties, err := core.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties

	w._rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowSandboxDisplayData) String() string {
	if len(w._rawJSON) > 0 {
		if value, err := core.StringifyJSON(w._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type FolderEntitiesListRequestEntityStatus string

const (
	FolderEntitiesListRequestEntityStatusActive   FolderEntitiesListRequestEntityStatus = "ACTIVE"
	FolderEntitiesListRequestEntityStatusArchived FolderEntitiesListRequestEntityStatus = "ARCHIVED"
)

func NewFolderEntitiesListRequestEntityStatusFromString(s string) (FolderEntitiesListRequestEntityStatus, error) {
	switch s {
	case "ACTIVE":
		return FolderEntitiesListRequestEntityStatusActive, nil
	case "ARCHIVED":
		return FolderEntitiesListRequestEntityStatusArchived, nil
	}
	var t FolderEntitiesListRequestEntityStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (f FolderEntitiesListRequestEntityStatus) Ptr() *FolderEntitiesListRequestEntityStatus {
	return &f
}
