// This file was auto-generated by Fern from our API Definition.

package api

type ListTestSuiteTestCasesRequest struct {
	// Number of results to return per page.
	Limit *int `json:"-"`
	// The initial index from which to return the results.
	Offset *int `json:"-"`
}
