// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/vellum-ai/vellum-client-go/core"
	time "time"
)

type ExecuteWorkflowDeploymentStreamRequest struct {
	// A mapping from input name to value.
	Inputs map[string]interface{} `json:"inputs,omitempty" url:"-"`
	// The name or ID of a workflow trigger to use for this execution. If not specified, then a default manual trigger will be chosen.
	Trigger *string `json:"trigger,omitempty" url:"-"`
	// Optionally specify a release tag if you want to pin to a specific release of the Workflow Deployment
	ReleaseTag *string `json:"release_tag,omitempty" url:"-"`
	// Optionally include a unique identifier for tracking purposes. Must be unique within a given Workspace.
	ExternalId *string `json:"external_id,omitempty" url:"-"`
	// Arbitrary JSON metadata associated with this request. Can be used to capture additional monitoring data such as user id, session id, etc. for future analysis.
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"-"`
	// The ID of a previous workflow execution to reference for context.
	PreviousExecutionId *string `json:"previous_execution_id,omitempty" url:"-"`
}

type WorkflowDeploymentsListRequest struct {
	// Number of results to return per page.
	Limit *int `json:"-" url:"limit,omitempty"`
	// The initial index from which to return the results.
	Offset *int `json:"-" url:"offset,omitempty"`
	// Which field to use when ordering the results.
	Ordering *string `json:"-" url:"ordering,omitempty"`
	// status
	Status *WorkflowDeploymentsListRequestStatus `json:"-" url:"status,omitempty"`
}

type ListWorkflowDeploymentEventExecutionsRequest struct {
	Filters *string `json:"-" url:"filters,omitempty"`
	// Number of executions to return per page.
	Limit *int `json:"-" url:"limit,omitempty"`
	// The initial index from which to return the executions.
	Offset   *int    `json:"-" url:"offset,omitempty"`
	Ordering *string `json:"-" url:"ordering,omitempty"`
}

type ListWorkflowDeploymentReleasesRequest struct {
	// Number of results to return per page.
	Limit *int `json:"-" url:"limit,omitempty"`
	// The initial index from which to return the results.
	Offset *int `json:"-" url:"offset,omitempty"`
	// Which field to use when ordering the results.
	Ordering *string `json:"-" url:"ordering,omitempty"`
}

type ListWorkflowReleaseTagsRequest struct {
	// Number of results to return per page.
	Limit *int `json:"-" url:"limit,omitempty"`
	// The initial index from which to return the results.
	Offset *int `json:"-" url:"offset,omitempty"`
	// Which field to use when ordering the results.
	Ordering *string                               `json:"-" url:"ordering,omitempty"`
	Source   *ListWorkflowReleaseTagsRequestSource `json:"-" url:"source,omitempty"`
}

type PaginatedSlimWorkflowDeploymentList struct {
	Count    *int                      `json:"count,omitempty" url:"count,omitempty"`
	Next     *string                   `json:"next,omitempty" url:"next,omitempty"`
	Previous *string                   `json:"previous,omitempty" url:"previous,omitempty"`
	Results  []*SlimWorkflowDeployment `json:"results,omitempty" url:"results,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PaginatedSlimWorkflowDeploymentList) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaginatedSlimWorkflowDeploymentList) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginatedSlimWorkflowDeploymentList
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginatedSlimWorkflowDeploymentList(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginatedSlimWorkflowDeploymentList) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PaginatedWorkflowDeploymentReleaseList struct {
	Count    *int                         `json:"count,omitempty" url:"count,omitempty"`
	Next     *string                      `json:"next,omitempty" url:"next,omitempty"`
	Previous *string                      `json:"previous,omitempty" url:"previous,omitempty"`
	Results  []*WorkflowDeploymentRelease `json:"results,omitempty" url:"results,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PaginatedWorkflowDeploymentReleaseList) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaginatedWorkflowDeploymentReleaseList) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginatedWorkflowDeploymentReleaseList
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginatedWorkflowDeploymentReleaseList(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginatedWorkflowDeploymentReleaseList) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PaginatedWorkflowReleaseTagReadList struct {
	Count    *int                      `json:"count,omitempty" url:"count,omitempty"`
	Next     *string                   `json:"next,omitempty" url:"next,omitempty"`
	Previous *string                   `json:"previous,omitempty" url:"previous,omitempty"`
	Results  []*WorkflowReleaseTagRead `json:"results,omitempty" url:"results,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PaginatedWorkflowReleaseTagReadList) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaginatedWorkflowReleaseTagReadList) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginatedWorkflowReleaseTagReadList
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginatedWorkflowReleaseTagReadList(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginatedWorkflowReleaseTagReadList) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// A subset of a Workflow Deployment's full details.
type SlimWorkflowDeployment struct {
	Id string `json:"id" url:"id"`
	// A name that uniquely identifies this workflow deployment within its workspace
	Name string `json:"name" url:"name"`
	// A human-readable label for the workflow deployment
	Label string `json:"label" url:"label"`
	// The current status of the workflow deployment
	//
	// * `ACTIVE` - Active
	// * `ARCHIVED` - Archived
	// * `PENDING_DELETION` - Pending Deletion
	Status *EntityStatus `json:"status,omitempty" url:"status,omitempty"`
	// Deprecated. The value returned will always be 'PRODUCTION'.
	Environment    *EnvironmentEnum `json:"environment,omitempty" url:"environment,omitempty"`
	Created        time.Time        `json:"created" url:"created"`
	LastDeployedOn time.Time        `json:"last_deployed_on" url:"last_deployed_on"`
	// The input variables this Workflow Deployment expects to receive values for when it is executed.
	InputVariables []*VellumVariable `json:"input_variables" url:"input_variables"`
	// The output variables this Workflow Deployment will produce when it is executed.
	OutputVariables []*VellumVariable `json:"output_variables" url:"output_variables"`
	// A human-readable description of the workflow deployment
	Description *string `json:"description,omitempty" url:"description,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SlimWorkflowDeployment) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SlimWorkflowDeployment) UnmarshalJSON(data []byte) error {
	type embed SlimWorkflowDeployment
	var unmarshaler = struct {
		embed
		Created        *core.DateTime `json:"created"`
		LastDeployedOn *core.DateTime `json:"last_deployed_on"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = SlimWorkflowDeployment(unmarshaler.embed)
	s.Created = unmarshaler.Created.Time()
	s.LastDeployedOn = unmarshaler.LastDeployedOn.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SlimWorkflowDeployment) MarshalJSON() ([]byte, error) {
	type embed SlimWorkflowDeployment
	var marshaler = struct {
		embed
		Created        *core.DateTime `json:"created"`
		LastDeployedOn *core.DateTime `json:"last_deployed_on"`
	}{
		embed:          embed(*s),
		Created:        core.NewDateTime(s.Created),
		LastDeployedOn: core.NewDateTime(s.LastDeployedOn),
	}
	return json.Marshal(marshaler)
}

func (s *SlimWorkflowDeployment) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SlimWorkflowExecutionRead struct {
	SpanId        string                                         `json:"span_id" url:"span_id"`
	Start         time.Time                                      `json:"start" url:"start"`
	End           *time.Time                                     `json:"end,omitempty" url:"end,omitempty"`
	Inputs        []*ExecutionVellumValue                        `json:"inputs" url:"inputs"`
	Outputs       []*ExecutionVellumValue                        `json:"outputs" url:"outputs"`
	Error         *WorkflowError                                 `json:"error,omitempty" url:"error,omitempty"`
	UsageResults  []*WorkflowExecutionUsageResult                `json:"usage_results,omitempty" url:"usage_results,omitempty"`
	ParentContext *WorkflowDeploymentParentContext               `json:"parent_context,omitempty" url:"parent_context,omitempty"`
	LatestActual  *WorkflowExecutionActual                       `json:"latest_actual,omitempty" url:"latest_actual,omitempty"`
	MetricResults []*WorkflowExecutionViewOnlineEvalMetricResult `json:"metric_results" url:"metric_results"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SlimWorkflowExecutionRead) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SlimWorkflowExecutionRead) UnmarshalJSON(data []byte) error {
	type embed SlimWorkflowExecutionRead
	var unmarshaler = struct {
		embed
		Start *core.DateTime `json:"start"`
		End   *core.DateTime `json:"end,omitempty"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = SlimWorkflowExecutionRead(unmarshaler.embed)
	s.Start = unmarshaler.Start.Time()
	s.End = unmarshaler.End.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SlimWorkflowExecutionRead) MarshalJSON() ([]byte, error) {
	type embed SlimWorkflowExecutionRead
	var marshaler = struct {
		embed
		Start *core.DateTime `json:"start"`
		End   *core.DateTime `json:"end,omitempty"`
	}{
		embed: embed(*s),
		Start: core.NewDateTime(s.Start),
		End:   core.NewOptionalDateTime(s.End),
	}
	return json.Marshal(marshaler)
}

func (s *SlimWorkflowExecutionRead) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type WorkflowDeploymentEventExecutionsResponse struct {
	Count   int                          `json:"count" url:"count"`
	Results []*SlimWorkflowExecutionRead `json:"results" url:"results"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (w *WorkflowDeploymentEventExecutionsResponse) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkflowDeploymentEventExecutionsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowDeploymentEventExecutionsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkflowDeploymentEventExecutionsResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties

	w._rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowDeploymentEventExecutionsResponse) String() string {
	if len(w._rawJSON) > 0 {
		if value, err := core.StringifyJSON(w._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WorkflowDeploymentHistoryItem struct {
	Id                   string    `json:"id" url:"id"`
	WorkflowDeploymentId string    `json:"workflow_deployment_id" url:"workflow_deployment_id"`
	Timestamp            time.Time `json:"timestamp" url:"timestamp"`
	// A human-readable label for the workflow deployment
	Label string `json:"label" url:"label"`
	// A name that uniquely identifies this workflow deployment within its workspace
	Name            string            `json:"name" url:"name"`
	InputVariables  []*VellumVariable `json:"input_variables" url:"input_variables"`
	OutputVariables []*VellumVariable `json:"output_variables" url:"output_variables"`
	// A human-readable description of the workflow deployment
	Description *string `json:"description,omitempty" url:"description,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (w *WorkflowDeploymentHistoryItem) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkflowDeploymentHistoryItem) UnmarshalJSON(data []byte) error {
	type embed WorkflowDeploymentHistoryItem
	var unmarshaler = struct {
		embed
		Timestamp *core.DateTime `json:"timestamp"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WorkflowDeploymentHistoryItem(unmarshaler.embed)
	w.Timestamp = unmarshaler.Timestamp.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties

	w._rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowDeploymentHistoryItem) MarshalJSON() ([]byte, error) {
	type embed WorkflowDeploymentHistoryItem
	var marshaler = struct {
		embed
		Timestamp *core.DateTime `json:"timestamp"`
	}{
		embed:     embed(*w),
		Timestamp: core.NewDateTime(w.Timestamp),
	}
	return json.Marshal(marshaler)
}

func (w *WorkflowDeploymentHistoryItem) String() string {
	if len(w._rawJSON) > 0 {
		if value, err := core.StringifyJSON(w._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WorkflowDeploymentRelease struct {
	Id              string                                       `json:"id" url:"id"`
	Created         time.Time                                    `json:"created" url:"created"`
	Environment     *ReleaseEnvironment                          `json:"environment" url:"environment"`
	CreatedBy       *ReleaseCreatedBy                            `json:"created_by,omitempty" url:"created_by,omitempty"`
	WorkflowVersion *WorkflowDeploymentReleaseWorkflowVersion    `json:"workflow_version" url:"workflow_version"`
	Deployment      *WorkflowDeploymentReleaseWorkflowDeployment `json:"deployment" url:"deployment"`
	Description     *string                                      `json:"description,omitempty" url:"description,omitempty"`
	ReleaseTags     []*ReleaseReleaseTag                         `json:"release_tags" url:"release_tags"`
	Reviews         []*SlimReleaseReview                         `json:"reviews" url:"reviews"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (w *WorkflowDeploymentRelease) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkflowDeploymentRelease) UnmarshalJSON(data []byte) error {
	type embed WorkflowDeploymentRelease
	var unmarshaler = struct {
		embed
		Created *core.DateTime `json:"created"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WorkflowDeploymentRelease(unmarshaler.embed)
	w.Created = unmarshaler.Created.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties

	w._rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowDeploymentRelease) MarshalJSON() ([]byte, error) {
	type embed WorkflowDeploymentRelease
	var marshaler = struct {
		embed
		Created *core.DateTime `json:"created"`
	}{
		embed:   embed(*w),
		Created: core.NewDateTime(w.Created),
	}
	return json.Marshal(marshaler)
}

func (w *WorkflowDeploymentRelease) String() string {
	if len(w._rawJSON) > 0 {
		if value, err := core.StringifyJSON(w._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WorkflowDeploymentReleaseWorkflowDeployment struct {
	Id   string `json:"id" url:"id"`
	Name string `json:"name" url:"name"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (w *WorkflowDeploymentReleaseWorkflowDeployment) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkflowDeploymentReleaseWorkflowDeployment) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowDeploymentReleaseWorkflowDeployment
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkflowDeploymentReleaseWorkflowDeployment(value)

	extraProperties, err := core.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties

	w._rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowDeploymentReleaseWorkflowDeployment) String() string {
	if len(w._rawJSON) > 0 {
		if value, err := core.StringifyJSON(w._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WorkflowDeploymentReleaseWorkflowVersion struct {
	Id              string            `json:"id" url:"id"`
	InputVariables  []*VellumVariable `json:"input_variables" url:"input_variables"`
	OutputVariables []*VellumVariable `json:"output_variables" url:"output_variables"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (w *WorkflowDeploymentReleaseWorkflowVersion) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkflowDeploymentReleaseWorkflowVersion) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowDeploymentReleaseWorkflowVersion
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkflowDeploymentReleaseWorkflowVersion(value)

	extraProperties, err := core.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties

	w._rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowDeploymentReleaseWorkflowVersion) String() string {
	if len(w._rawJSON) > 0 {
		if value, err := core.StringifyJSON(w._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WorkflowEventExecutionRead struct {
	SpanId        string                                         `json:"span_id" url:"span_id"`
	Start         time.Time                                      `json:"start" url:"start"`
	End           *time.Time                                     `json:"end,omitempty" url:"end,omitempty"`
	Inputs        []*ExecutionVellumValue                        `json:"inputs" url:"inputs"`
	Outputs       []*ExecutionVellumValue                        `json:"outputs" url:"outputs"`
	Error         *WorkflowError                                 `json:"error,omitempty" url:"error,omitempty"`
	UsageResults  []*WorkflowExecutionUsageResult                `json:"usage_results,omitempty" url:"usage_results,omitempty"`
	ParentContext *WorkflowDeploymentParentContext               `json:"parent_context,omitempty" url:"parent_context,omitempty"`
	LatestActual  *WorkflowExecutionActual                       `json:"latest_actual,omitempty" url:"latest_actual,omitempty"`
	MetricResults []*WorkflowExecutionViewOnlineEvalMetricResult `json:"metric_results" url:"metric_results"`
	Spans         []*VellumSpan                                  `json:"spans" url:"spans"`
	State         map[string]interface{}                         `json:"state,omitempty" url:"state,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (w *WorkflowEventExecutionRead) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkflowEventExecutionRead) UnmarshalJSON(data []byte) error {
	type embed WorkflowEventExecutionRead
	var unmarshaler = struct {
		embed
		Start *core.DateTime `json:"start"`
		End   *core.DateTime `json:"end,omitempty"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WorkflowEventExecutionRead(unmarshaler.embed)
	w.Start = unmarshaler.Start.Time()
	w.End = unmarshaler.End.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties

	w._rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowEventExecutionRead) MarshalJSON() ([]byte, error) {
	type embed WorkflowEventExecutionRead
	var marshaler = struct {
		embed
		Start *core.DateTime `json:"start"`
		End   *core.DateTime `json:"end,omitempty"`
	}{
		embed: embed(*w),
		Start: core.NewDateTime(w.Start),
		End:   core.NewOptionalDateTime(w.End),
	}
	return json.Marshal(marshaler)
}

func (w *WorkflowEventExecutionRead) String() string {
	if len(w._rawJSON) > 0 {
		if value, err := core.StringifyJSON(w._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WorkflowExecutionActual struct {
	Output    *ExecutionVellumValue  `json:"output" url:"output"`
	Timestamp time.Time              `json:"timestamp" url:"timestamp"`
	Quality   *float64               `json:"quality,omitempty" url:"quality,omitempty"`
	Metadata  map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (w *WorkflowExecutionActual) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkflowExecutionActual) UnmarshalJSON(data []byte) error {
	type embed WorkflowExecutionActual
	var unmarshaler = struct {
		embed
		Timestamp *core.DateTime `json:"timestamp"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WorkflowExecutionActual(unmarshaler.embed)
	w.Timestamp = unmarshaler.Timestamp.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties

	w._rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowExecutionActual) MarshalJSON() ([]byte, error) {
	type embed WorkflowExecutionActual
	var marshaler = struct {
		embed
		Timestamp *core.DateTime `json:"timestamp"`
	}{
		embed:     embed(*w),
		Timestamp: core.NewDateTime(w.Timestamp),
	}
	return json.Marshal(marshaler)
}

func (w *WorkflowExecutionActual) String() string {
	if len(w._rawJSON) > 0 {
		if value, err := core.StringifyJSON(w._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WorkflowExecutionViewOnlineEvalMetricResult struct {
	Outputs  []*ExecutionVellumValue `json:"outputs" url:"outputs"`
	Label    string                  `json:"label" url:"label"`
	MetricId string                  `json:"metric_id" url:"metric_id"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (w *WorkflowExecutionViewOnlineEvalMetricResult) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkflowExecutionViewOnlineEvalMetricResult) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowExecutionViewOnlineEvalMetricResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkflowExecutionViewOnlineEvalMetricResult(value)

	extraProperties, err := core.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties

	w._rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowExecutionViewOnlineEvalMetricResult) String() string {
	if len(w._rawJSON) > 0 {
		if value, err := core.StringifyJSON(w._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WorkflowReleaseTagRead struct {
	// The name of the Release Tag
	Name string `json:"name" url:"name"`
	// The source of how the Release Tag was originally created
	//
	// * `SYSTEM` - System
	// * `USER` - User
	Source ReleaseTagSource `json:"source" url:"source"`
	// Deprecated. Reference the `release` field instead.
	HistoryItem *WorkflowReleaseTagWorkflowDeploymentHistoryItem `json:"history_item" url:"history_item"`
	// The Release that this Release Tag points to.
	Release *ReleaseTagRelease `json:"release" url:"release"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (w *WorkflowReleaseTagRead) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkflowReleaseTagRead) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowReleaseTagRead
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkflowReleaseTagRead(value)

	extraProperties, err := core.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties

	w._rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowReleaseTagRead) String() string {
	if len(w._rawJSON) > 0 {
		if value, err := core.StringifyJSON(w._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WorkflowReleaseTagWorkflowDeploymentHistoryItem struct {
	Id        string    `json:"id" url:"id"`
	Timestamp time.Time `json:"timestamp" url:"timestamp"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (w *WorkflowReleaseTagWorkflowDeploymentHistoryItem) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkflowReleaseTagWorkflowDeploymentHistoryItem) UnmarshalJSON(data []byte) error {
	type embed WorkflowReleaseTagWorkflowDeploymentHistoryItem
	var unmarshaler = struct {
		embed
		Timestamp *core.DateTime `json:"timestamp"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WorkflowReleaseTagWorkflowDeploymentHistoryItem(unmarshaler.embed)
	w.Timestamp = unmarshaler.Timestamp.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties

	w._rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowReleaseTagWorkflowDeploymentHistoryItem) MarshalJSON() ([]byte, error) {
	type embed WorkflowReleaseTagWorkflowDeploymentHistoryItem
	var marshaler = struct {
		embed
		Timestamp *core.DateTime `json:"timestamp"`
	}{
		embed:     embed(*w),
		Timestamp: core.NewDateTime(w.Timestamp),
	}
	return json.Marshal(marshaler)
}

func (w *WorkflowReleaseTagWorkflowDeploymentHistoryItem) String() string {
	if len(w._rawJSON) > 0 {
		if value, err := core.StringifyJSON(w._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type ListWorkflowReleaseTagsRequestSource string

const (
	ListWorkflowReleaseTagsRequestSourceSystem ListWorkflowReleaseTagsRequestSource = "SYSTEM"
	ListWorkflowReleaseTagsRequestSourceUser   ListWorkflowReleaseTagsRequestSource = "USER"
)

func NewListWorkflowReleaseTagsRequestSourceFromString(s string) (ListWorkflowReleaseTagsRequestSource, error) {
	switch s {
	case "SYSTEM":
		return ListWorkflowReleaseTagsRequestSourceSystem, nil
	case "USER":
		return ListWorkflowReleaseTagsRequestSourceUser, nil
	}
	var t ListWorkflowReleaseTagsRequestSource
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListWorkflowReleaseTagsRequestSource) Ptr() *ListWorkflowReleaseTagsRequestSource {
	return &l
}

type WorkflowDeploymentsListRequestStatus string

const (
	WorkflowDeploymentsListRequestStatusActive          WorkflowDeploymentsListRequestStatus = "ACTIVE"
	WorkflowDeploymentsListRequestStatusArchived        WorkflowDeploymentsListRequestStatus = "ARCHIVED"
	WorkflowDeploymentsListRequestStatusPendingDeletion WorkflowDeploymentsListRequestStatus = "PENDING_DELETION"
)

func NewWorkflowDeploymentsListRequestStatusFromString(s string) (WorkflowDeploymentsListRequestStatus, error) {
	switch s {
	case "ACTIVE":
		return WorkflowDeploymentsListRequestStatusActive, nil
	case "ARCHIVED":
		return WorkflowDeploymentsListRequestStatusArchived, nil
	case "PENDING_DELETION":
		return WorkflowDeploymentsListRequestStatusPendingDeletion, nil
	}
	var t WorkflowDeploymentsListRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WorkflowDeploymentsListRequestStatus) Ptr() *WorkflowDeploymentsListRequestStatus {
	return &w
}

type PatchedWorkflowReleaseTagUpdateRequest struct {
	// The ID of the Workflow Deployment History Item to tag
	HistoryItemId *string `json:"history_item_id,omitempty" url:"-"`
}
