// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/vellum-ai/vellum-client-go/core"
	time "time"
)

type WorkflowRunNodeRequest struct {
	Files  map[string]string      `json:"files,omitempty" url:"-"`
	Node   string                 `json:"node" url:"-"`
	Inputs map[string]interface{} `json:"inputs,omitempty" url:"-"`
}

type WorkflowsPullRequest struct {
	ExcludeCode    *bool `json:"-" url:"exclude_code,omitempty"`
	ExcludeDisplay *bool `json:"-" url:"exclude_display,omitempty"`
	IncludeJSON    *bool `json:"-" url:"include_json,omitempty"`
	IncludeSandbox *bool `json:"-" url:"include_sandbox,omitempty"`
	// Release tag to use when pulling from deployment (implies deployment-only lookup)
	ReleaseTag *string `json:"-" url:"release_tag,omitempty"`
	Strict     *bool   `json:"-" url:"strict,omitempty"`
	// Semantic version range to validate against the Workflow SDK version (e.g., '>=1.0.0,<1.2.3')
	Version *string `json:"-" url:"version,omitempty"`
}

type WorkflowPushRequest struct {
	// The execution configuration of the workflow. If not provided, it will be derived from the artifact.
	ExecConfig        *WorkflowPushExecConfig              `json:"exec_config,omitempty" url:"-"`
	WorkflowSandboxID *string                              `json:"workflow_sandbox_id,omitempty" url:"-"`
	DeploymentConfig  *WorkflowPushDeploymentConfigRequest `json:"deployment_config,omitempty" url:"-"`
	// List of dataset rows with inputs for scenarios.
	Dataset []*DatasetRowPushRequest `json:"dataset,omitempty" url:"-"`
	DryRun  *bool                    `json:"dry_run,omitempty" url:"-"`
	Strict  *bool                    `json:"strict,omitempty" url:"-"`
}

type WorkflowsRetrieveStateRequest struct {
}

type SerializeWorkflowFilesRequest struct {
	Files        map[string]interface{} `json:"files,omitempty" url:"-"`
	Module       *string                `json:"module,omitempty" url:"-"`
	RunnerConfig *RunnerConfigRequest   `json:"runner_config,omitempty" url:"-"`
}

type CheckWorkflowExecutionStatusError struct {
	Message *string                          `json:"message,omitempty" url:"message,omitempty"`
	Code    *WorkflowExecutionEventErrorCode `json:"code,omitempty" url:"code,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CheckWorkflowExecutionStatusError) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CheckWorkflowExecutionStatusError) UnmarshalJSON(data []byte) error {
	type unmarshaler CheckWorkflowExecutionStatusError
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CheckWorkflowExecutionStatusError(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CheckWorkflowExecutionStatusError) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Response serializer for workflow execution status check.
type CheckWorkflowExecutionStatusResponse struct {
	Status             WorkflowResultEventState           `json:"status" url:"status"`
	Outputs            map[string]interface{}             `json:"outputs,omitempty" url:"outputs,omitempty"`
	Error              *CheckWorkflowExecutionStatusError `json:"error,omitempty" url:"error,omitempty"`
	ExecutionID        string                             `json:"execution_id" url:"execution_id"`
	ExecutionDetailURL *string                            `json:"execution_detail_url,omitempty" url:"execution_detail_url,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CheckWorkflowExecutionStatusResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CheckWorkflowExecutionStatusResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CheckWorkflowExecutionStatusResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CheckWorkflowExecutionStatusResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CheckWorkflowExecutionStatusResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type DatasetRowPushRequest struct {
	ID                *string                  `json:"id,omitempty" url:"id,omitempty"`
	Label             string                   `json:"label" url:"label"`
	Inputs            map[string]interface{}   `json:"inputs" url:"inputs"`
	Mocks             []map[string]interface{} `json:"mocks,omitempty" url:"mocks,omitempty"`
	WorkflowTriggerID *string                  `json:"workflow_trigger_id,omitempty" url:"workflow_trigger_id,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (d *DatasetRowPushRequest) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DatasetRowPushRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler DatasetRowPushRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DatasetRowPushRequest(value)

	extraProperties, err := core.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties

	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DatasetRowPushRequest) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type RunnerConfigRequest struct {
	ContainerImageName          *string `json:"container_image_name,omitempty" url:"container_image_name,omitempty"`
	ContainerImageTag           *string `json:"container_image_tag,omitempty" url:"container_image_tag,omitempty"`
	CodegenVersion              *string `json:"codegen_version,omitempty" url:"codegen_version,omitempty"`
	SdkVersion                  *string `json:"sdk_version,omitempty" url:"sdk_version,omitempty"`
	IsDeploymentInliningEnabled *bool   `json:"is_deployment_inlining_enabled,omitempty" url:"is_deployment_inlining_enabled,omitempty"`
	ServerVersion               *string `json:"server_version,omitempty" url:"server_version,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (r *RunnerConfigRequest) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RunnerConfigRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RunnerConfigRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RunnerConfigRequest(value)

	extraProperties, err := core.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties

	r._rawJSON = json.RawMessage(data)
	return nil
}

func (r *RunnerConfigRequest) String() string {
	if len(r._rawJSON) > 0 {
		if value, err := core.StringifyJSON(r._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type WorkflowPushDeploymentConfigRequest struct {
	Label              *string  `json:"label,omitempty" url:"label,omitempty"`
	Name               *string  `json:"name,omitempty" url:"name,omitempty"`
	Description        *string  `json:"description,omitempty" url:"description,omitempty"`
	ReleaseTags        []string `json:"release_tags,omitempty" url:"release_tags,omitempty"`
	ReleaseDescription *string  `json:"release_description,omitempty" url:"release_description,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (w *WorkflowPushDeploymentConfigRequest) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkflowPushDeploymentConfigRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowPushDeploymentConfigRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkflowPushDeploymentConfigRequest(value)

	extraProperties, err := core.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties

	w._rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowPushDeploymentConfigRequest) String() string {
	if len(w._rawJSON) > 0 {
		if value, err := core.StringifyJSON(w._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WorkflowPushExecConfig = string

type WorkflowPushResponse struct {
	WorkflowSandboxID    string                 `json:"workflow_sandbox_id" url:"workflow_sandbox_id"`
	WorkflowDeploymentID *string                `json:"workflow_deployment_id,omitempty" url:"workflow_deployment_id,omitempty"`
	ProposedDiffs        map[string]interface{} `json:"proposed_diffs,omitempty" url:"proposed_diffs,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (w *WorkflowPushResponse) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkflowPushResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowPushResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkflowPushResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties

	w._rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowPushResponse) String() string {
	if len(w._rawJSON) > 0 {
		if value, err := core.StringifyJSON(w._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// The latest execution state of a given Workflow Execution
type WorkflowResolvedState struct {
	TraceID         string                 `json:"trace_id" url:"trace_id"`
	Timestamp       time.Time              `json:"timestamp" url:"timestamp"`
	SpanID          string                 `json:"span_id" url:"span_id"`
	State           map[string]interface{} `json:"state" url:"state"`
	PreviousSpanID  *string                `json:"previous_span_id,omitempty" url:"previous_span_id,omitempty"`
	PreviousTraceID *string                `json:"previous_trace_id,omitempty" url:"previous_trace_id,omitempty"`
	RootSpanID      *string                `json:"root_span_id,omitempty" url:"root_span_id,omitempty"`
	RootTraceID     *string                `json:"root_trace_id,omitempty" url:"root_trace_id,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (w *WorkflowResolvedState) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WorkflowResolvedState) UnmarshalJSON(data []byte) error {
	type embed WorkflowResolvedState
	var unmarshaler = struct {
		embed
		Timestamp *core.DateTime `json:"timestamp"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WorkflowResolvedState(unmarshaler.embed)
	w.Timestamp = unmarshaler.Timestamp.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties

	w._rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowResolvedState) MarshalJSON() ([]byte, error) {
	type embed WorkflowResolvedState
	var marshaler = struct {
		embed
		Timestamp *core.DateTime `json:"timestamp"`
	}{
		embed:     embed(*w),
		Timestamp: core.NewDateTime(w.Timestamp),
	}
	return json.Marshal(marshaler)
}

func (w *WorkflowResolvedState) String() string {
	if len(w._rawJSON) > 0 {
		if value, err := core.StringifyJSON(w._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WorkflowSandboxExecuteNodeResponse struct {
	Name                   string
	NodeExecutionFulfilled *NodeExecutionFulfilledEvent
	NodeExecutionRejected  *NodeExecutionRejectedEvent
}

func (w *WorkflowSandboxExecuteNodeResponse) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Name string `json:"name"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	w.Name = unmarshaler.Name
	if unmarshaler.Name == "" {
		return fmt.Errorf("%T did not include discriminant name", w)
	}
	switch unmarshaler.Name {
	case "node.execution.fulfilled":
		value := new(NodeExecutionFulfilledEvent)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		w.NodeExecutionFulfilled = value
	case "node.execution.rejected":
		value := new(NodeExecutionRejectedEvent)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		w.NodeExecutionRejected = value
	}
	return nil
}

func (w WorkflowSandboxExecuteNodeResponse) MarshalJSON() ([]byte, error) {
	if w.NodeExecutionFulfilled != nil {
		return core.MarshalJSONWithExtraProperty(w.NodeExecutionFulfilled, "name", "node.execution.fulfilled")
	}
	if w.NodeExecutionRejected != nil {
		return core.MarshalJSONWithExtraProperty(w.NodeExecutionRejected, "name", "node.execution.rejected")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", w)
}

type WorkflowSandboxExecuteNodeResponseVisitor interface {
	VisitNodeExecutionFulfilled(*NodeExecutionFulfilledEvent) error
	VisitNodeExecutionRejected(*NodeExecutionRejectedEvent) error
}

func (w *WorkflowSandboxExecuteNodeResponse) Accept(visitor WorkflowSandboxExecuteNodeResponseVisitor) error {
	if w.NodeExecutionFulfilled != nil {
		return visitor.VisitNodeExecutionFulfilled(w.NodeExecutionFulfilled)
	}
	if w.NodeExecutionRejected != nil {
		return visitor.VisitNodeExecutionRejected(w.NodeExecutionRejected)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", w)
}

type WorkflowExecutionStatusRequest struct {
}
